-- Create users table
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sessions (
    id SERIAL PRIMARY KEY,
    token VARCHAR(255) UNIQUE NOT NULL,
    user_id INTEGER NOT NULL REFERENCES users(id),
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_sessions_token ON sessions(token);
CREATE INDEX idx_sessions_expires ON sessions(expires_at);

-- Create posts table
CREATE TABLE IF NOT EXISTS posts (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    author_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Insert sample data
INSERT INTO users (name, password) VALUES 
    ('John Doe&Admin User', 'U89:0^$v==6S""j^Uf6d'),
    ('Jane Smith', 'password123'),
    ('Bob Johnson', 'mypassword'),
    ('Alice Williams', 'alicepass'),
    ('Charlie Brown', 'charlie123'),
    ('Emily Clark', 'emilysecure'),
    ('David Martinez', 'davidsafe'),
    ('Sophia Turner', 'sophiapass'),
    ('Michael Lee', 'michaelpw'),
    ('Linda Kim', 'lindakim2025'),
    ('Chris Evans', 'chrisevans321'),
    ('Børge Smørrebrødsen', 'FIRE{GR4PHQL_1D0R_S1D3_D00R}'), -- Here is the flag
    ('Ethan Wright', 'ethanwright'),
    ('Grace Hall', 'gracehall'),
    ('Ryan King', 'ryanking'),
    ('dolorem','Nesciunt voluptas pariatur quod explicabo quibusdam aut culpa.'),
    ('asperiores','Impedit harum quo quod officia.'),
    ('ut','Blanditiis maxime et deserunt rerum et vero necessitatibus.'),
    ('quo','Pariatur debitis blanditiis enim ut sed iusto.'),
    ('blanditiis','Dolorem quae et quaerat facilis autem qui et.'),
    ('dolore','Fuga recusandae iusto nobis repudiandae molestiae similique nesciunt.'),
    ('amet','Corporis consequatur minus sit ipsam qui.'),
    ('aut','Sit harum praesentium qui cupiditate adipisci in.'),
    ('temporibus','Praesentium eum doloremque et qui.'),
    ('hic','Cum ea incidunt sint commodi perferendis.'),
    ('magni','Voluptatem aut corporis dicta at delectus libero rerum.'),
    ('modi','Fuga praesentium sequi veritatis esse itaque tenetur autem repellendus.'),
    ('est','Et sequi qui iure sapiente dolorem corporis natus quia.'),
    ('error','Quibusdam molestias qui molestiae.'),
    ('vel','Tenetur dolore accusantium sed quia.'),
    ('alias','Atque et inventore et quod reiciendis aut.'),
    ('ea','Reprehenderit nisi voluptas repudiandae quia ab harum.'),
    ('aliquid','Ipsum architecto explicabo repudiandae vero cumque tempora hic eligendi.'),
    ('optio','Doloribus quo aut omnis eaque.'),
    ('excepturi','Earum qui in est reprehenderit reprehenderit in consectetur sit.'),
    ('minima','Minus a labore eum aut velit ut.'),
    ('id','Cupiditate voluptate neque dicta voluptates aliquam.'),
    ('et','Ratione non nostrum voluptatum facilis.'),
    ('tempora','Dolor accusamus voluptas cum nihil.'),
    ('facere','Temporibus animi optio velit cum.'),
    ('molestiae','Explicabo dolore non dicta voluptates officia sed qui.'),
    ('ab','Earum laborum amet voluptas exercitationem illo qui.'),
    ('expedita','Itaque suscipit nulla eligendi labore porro esse sapiente laudantium.'),
    ('illum','Et corrupti sed omnis qui.'),
    ('eos','Et consequatur aliquid nostrum facilis quia.'),
    ('consequatur','Consequatur doloribus quod aliquid a quas officiis.'),
    ('quos','Accusamus molestiae labore nihil cupiditate tenetur et.'),
    ('animi','Animi soluta quod iure sunt.'),
    ('sed','Quod sint maiores eum rerum ab.'),
    ('velit','Possimus et non nesciunt quae ab quia.'),
    ('sit','Enim voluptas eius voluptatem at iure alias iure.'),
    ('earum','Iure dolorem eum at sapiente quis nulla.'),
    ('vitae','Ut quae ipsum molestias quis pariatur.'),
    ('harum','Earum qui dolor temporibus voluptates.'),
    ('quas','Totam ullam unde qui.'),
    ('quis','Est voluptas repellat aperiam sit qui eveniet.'),
    ('similique','Repellat unde et quas.'),
    ('qui','Quaerat quisquam voluptatem asperiores ducimus harum aut eveniet.'),
    ('ipsa','Ut distinctio quod et reiciendis cum eos quia.'),
    ('provident','Ea modi dolorem saepe sit ipsam animi rerum.'),
    ('aperiam','Quia fugit accusantium maiores vitae.'),
    ('nihil','Ipsa quae soluta aut saepe.'),
    ('maxime','Quia ipsum quia exercitationem occaecati.'),
    ('odit','Minus nihil in repudiandae voluptatem quia quisquam.'),
    ('labore','Eos suscipit quasi ipsam nam.'),
    ('dolorum','Incidunt saepe voluptatem deserunt eligendi.'),
    ('quaerat','Dicta eos nisi fuga maxime dolore cupiditate.'),
    ('rerum','Aut perspiciatis et et blanditiis vero illo tenetur.'),
    ('eum','Quis ut error quis officia saepe.'),
    ('maiores','Perferendis consectetur placeat quasi est consequatur et dolorum.'),
    ('nemo','Voluptate omnis provident maiores debitis.'),
    ('dolores','Enim assumenda sed mollitia mollitia quos nesciunt sequi.'),
    ('nesciunt','Dolores ipsa beatae id vitae laboriosam ut et aut.'),
    ('ullam','Doloremque qui sit eum laboriosam.'),
    ('voluptatem','Distinctio laboriosam quos voluptatem.'),
    ('itaque','Nisi quia qui eligendi ea dolores.'),
    ('facilis','Quibusdam repellendus odit veniam at.'),
    ('neque','Dolores aspernatur et maxime.'),
    ('soluta','Minima fugiat vero nostrum sunt occaecati velit voluptatem odit.'),
    ('dolor','Corporis repellat praesentium aut tenetur sunt.'),
    ('pariatur','Hic dolore provident omnis magnam quae animi aut ad.'),
    ('corrupti','Hic magnam dicta ut sed.');

INSERT INTO posts (title, content, author_id) VALUES 
    ('First Post', 'This is my first blog post about GraphQL.', 1),
    ('Learning GraphQL', 'GraphQL is a powerful query language for APIs.', 1),
    ('Database Design', 'Proper database design is crucial for scalability.', 2),
    ('Flask and GraphQL', 'Combining Flask with GraphQL creates powerful APIs.', 3),
    ('PostgreSQL Tips', 'Here are some tips for using PostgreSQL effectively.', 4),
    ('Frontend Frameworks', 'React, Vue, and Angular are popular choices.', 5),
    ('Docker Basics', 'Getting started with Docker containers for development.', 6),
    ('REST vs GraphQL', 'Comparing REST APIs with GraphQL.', 7),
    ('Unit Testing in Python', 'How to write effective unit tests in Python.', 8),
    ('Security Best Practices', 'Protecting your applications from common vulnerabilities.', 9),
    ('Continuous Integration', 'Automating your build and test processes.', 10),
    ('Scaling Web Apps', 'Techniques for scaling web applications.', 11),
    ('Async Programming', 'Understanding asynchronous programming in JavaScript.', 12),
    ('CSS Tricks', 'Some useful CSS tricks for modern web design.', 13),
    ('Microservices', 'Designing applications using microservices architecture.', 14),
    ('Debugging Techniques', 'Effective debugging strategies for developers.', 15),
    ('SQL Joins Explained', 'A simple explanation of SQL joins.', 2),
    ('Serverless Functions', 'Introduction to serverless computing.', 5),
    ('API Authentication', 'Methods for authenticating API requests.', 7),
    ('User Experience', 'Improving user experience with thoughtful design.', 12),
    ('Getting Started with Web Development', 'My journey into web development and the challenges I faced.', 16),
    ('Understanding Async/Await', 'A deep dive into asynchronous programming patterns.', 17),
    ('Building Responsive Layouts', 'Tips for creating layouts that work on all devices.', 18),
    ('Data Structures in Python', 'Essential data structures every Python developer should know.', 19),
    ('Machine Learning Basics', 'An introduction to machine learning concepts and algorithms.', 20),
    ('Cloud Computing Overview', 'Understanding the benefits of cloud computing platforms.', 21),
    ('Version Control with Git', 'Best practices for using Git in team environments.', 22),
    ('Performance Optimization', 'Techniques for optimizing web application performance.', 23),
    ('Mobile App Development', 'Comparing native vs hybrid mobile development approaches.', 24),
    ('Blockchain Technology', 'Understanding the fundamentals of blockchain and cryptocurrencies.', 25),
    ('AI and Ethics', 'Exploring the ethical implications of artificial intelligence.', 26),
    ('Web Security Fundamentals', 'Essential security practices for web developers.', 27),
    ('NoSQL vs SQL Databases', 'When to choose NoSQL over traditional SQL databases.', 28),
    ('Progressive Web Apps', 'Building web apps that feel like native applications.', 29),
    ('DevOps Culture', 'How DevOps practices improve software delivery.', 30),
    ('Code Review Best Practices', 'Making code reviews more effective and constructive.', 31),
    ('API Design Principles', 'Creating APIs that are intuitive and maintainable.', 32),
    ('Testing Strategies', 'Different approaches to testing software applications.', 33),
    ('Agile Development', 'Understanding agile methodologies and their benefits.', 34),
    ('Open Source Contribution', 'How to get started contributing to open source projects.', 35),
    ('Technical Writing', 'Writing clear and helpful technical documentation.', 36),
    ('Career Growth in Tech', 'Strategies for advancing your technology career.', 37),
    ('Remote Work Tips', 'Best practices for working effectively from home.', 38),
    ('Learning New Technologies', 'How to efficiently learn new programming languages and frameworks.', 39),
    ('Software Architecture', 'Principles of designing scalable software systems.', 40),
    ('UI/UX Design Principles', 'Creating user interfaces that are both beautiful and functional.', 41),
    ('Data Visualization', 'Techniques for presenting data in meaningful ways.', 42),
    ('Internet of Things', 'Exploring IoT development and its applications.', 43),
    ('Cybersecurity Awareness', 'Protecting yourself and your applications from cyber threats.', 44),
    ('Functional Programming', 'Understanding functional programming paradigms and benefits.', 45),
    ('Edge Computing', 'The future of distributed computing at the network edge.', 46),
    ('Quantum Computing Basics', 'An introduction to quantum computing concepts.', 47),
    ('Augmented Reality Development', 'Getting started with AR app development.', 48),
    ('Virtual Reality Applications', 'Exploring the possibilities of VR technology.', 49),
    ('Big Data Analytics', 'Processing and analyzing large datasets effectively.', 50),
    ('Cryptocurrency Development', 'Building applications on blockchain platforms.', 51),
    ('Game Development Fundamentals', 'Basic concepts for creating video games.', 52),
    ('Embedded Systems Programming', 'Programming for resource-constrained devices.', 53),
    ('Network Programming', 'Building applications that communicate over networks.', 54),
    ('Compiler Design', 'Understanding how programming languages are compiled.', 55),
    ('Operating Systems Concepts', 'Core principles of operating system design.', 56),
    ('Distributed Systems', 'Challenges and solutions in distributed computing.', 57),
    ('Computer Graphics', 'Fundamentals of rendering and visual computing.', 58),
    ('Natural Language Processing', 'Processing and understanding human language with AI.', 59),
    ('Computer Vision', 'Teaching computers to interpret and understand visual data.', 60),
    ('Robotics Programming', 'Programming autonomous robots and their control systems.', 61),
    ('Hardware Design', 'Basics of digital circuit design and computer architecture.', 62),
    ('Signal Processing', 'Analyzing and manipulating digital signals.', 63),
    ('Parallel Computing', 'Leveraging multiple processors for computational tasks.', 64),
    ('Database Administration', 'Managing and maintaining database systems.', 65),
    ('System Administration', 'Managing servers and IT infrastructure.', 66),
    ('Network Security', 'Protecting networks from unauthorized access and attacks.', 67),
    ('Digital Forensics', 'Investigating digital crimes and security incidents.', 68),
    ('Information Theory', 'Mathematical foundations of information and communication.', 69),
    ('Algorithm Design', 'Creating efficient algorithms for complex problems.', 70);